package edu.training.web.controller.concrete;

public enum CommandName {
    DO_AUTH, DO_REGISTRATION, DO_LOG_OUT, DO_ADD_ARTICLE, DO_EDIT_ARTICLE, DO_DELETE_ARTICLE,

    GO_TO_REGISTRATION_PAGE, GO_TO_LOGIN_PAGE, GO_TO_INDEX_PAGE, GO_TO_ARTICLE_PAGE,

    GO_TO_MANAGE_USERS_PAGE, GO_TO_ADD_ARTICLE_PAGE, GO_TO_EDIT_ARTICLE_PAGE,

    SELECT_ARTICLE_TO_EDIT, SELECT_ARTICLE_TO_DELETE,

    SET_LOCALE,
    NO_SUCH_COMMAND
}
